import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import path from "node:path"

import { SDK_VERSION } from "./constants.mjs"
import { assertExactFiles, fail, readJson, sha256 } from "./file-utils.mjs"

export const RELEASE_NOTICE_INDEX = "THIRD-PARTY-NOTICES.md"

const packagedSources = Object.freeze([
  {
    component: "Locked npm production and Cargo runtime dependency inventory",
    source: "third-party/THIRD-PARTY-DEPENDENCIES.json",
    destination: "THIRD-PARTY-DEPENDENCIES.json",
  },
  {
    component: "Locked npm production and Cargo runtime dependency notices",
    source: "third-party/THIRD-PARTY-DEPENDENCIES.md",
    destination: "THIRD-PARTY-DEPENDENCIES.md",
  },
  {
    component: "Live2D Cubism SDK for Web",
    source: `vendor/live2d/cubism-sdk-${SDK_VERSION}/LICENSE.md`,
    destination: `live2d/cubism-sdk-${SDK_VERSION}/LICENSE.md`,
  },
  {
    component: "Live2D Cubism Core",
    source: `vendor/live2d/cubism-sdk-${SDK_VERSION}/Core/LICENSE.md`,
    destination: `live2d/cubism-sdk-${SDK_VERSION}/Core/LICENSE.md`,
  },
  {
    component: "Live2D Cubism Core redistributable files",
    source: `vendor/live2d/cubism-sdk-${SDK_VERSION}/Core/RedistributableFiles.txt`,
    destination: `live2d/cubism-sdk-${SDK_VERSION}/Core/RedistributableFiles.txt`,
  },
  {
    component: "Live2D Cubism Framework",
    source: `vendor/live2d/cubism-sdk-${SDK_VERSION}/Framework/LICENSE.md`,
    destination: `live2d/cubism-sdk-${SDK_VERSION}/Framework/LICENSE.md`,
  },
  {
    component: "Live2D Cubism SDK pinned upstream metadata",
    source: `vendor/live2d/cubism-sdk-${SDK_VERSION}/UPSTREAM.json`,
    destination: `live2d/cubism-sdk-${SDK_VERSION}/UPSTREAM.json`,
  },
  {
    component: "Live2D Cubism SDK reviewed file checksums",
    source: `vendor/live2d/cubism-sdk-${SDK_VERSION}/checksums.sha256`,
    destination: `live2d/cubism-sdk-${SDK_VERSION}/checksums.sha256`,
  },
  {
    component: "Bundled Hiyori model",
    source: "src-tauri/resources/characters/builtin-hiyori/NOTICE.txt",
    destination: "../characters/builtin-hiyori/NOTICE.txt",
    copyToLegal: false,
  },
])

export function getReleaseNoticeRoot(projectRoot) {
  return path.join(projectRoot, "src-tauri/resources/legal")
}

export function getReleaseNoticeEntries(projectRoot) {
  return packagedSources.map((entry) => ({
    ...entry,
    sourcePath: path.join(projectRoot, entry.source),
  }))
}

export function buildReleaseNoticeIndex(projectRoot) {
  const upstream = readJson(
    path.join(
      projectRoot,
      `vendor/live2d/cubism-sdk-${SDK_VERSION}/UPSTREAM.json`,
    ),
  )
  const hiyori = readJson(
    path.join(
      projectRoot,
      "src-tauri/resources/characters/builtin-hiyori/pack.json",
    ),
  )
  const dependencies = readJson(
    path.join(projectRoot, "third-party/THIRD-PARTY-DEPENDENCIES.json"),
  )
  const rows = getReleaseNoticeEntries(projectRoot)
    .map(
      (entry) =>
        `| ${entry.component} | [${entry.destination}](${entry.destination}) | \`${sha256(entry.sourcePath)}\` | \`${entry.source}\` |`,
    )
    .join("\n")

  return `# Third-Party Notices

This is the single index for third-party material packaged with Coding Wife. The linked dependency inventory, dependency notices, Live2D license, redistributable-file, provenance, checksum, and model-notice files are copied from the pinned repository sources listed below.

This index and its linked files are generated by \`scripts/licenses/dependency-notices.mjs\` and \`scripts/live2d/release-notices.mjs\`. Do not edit the packaged copies directly.

## Locked application dependencies

- npm production dependencies: \`${dependencies.summary.npm}\`
- Cargo runtime dependencies for \`${dependencies.generatedFrom.cargoTarget}\`: \`${dependencies.summary.cargo}\`
- pnpm lock SHA-256: \`${dependencies.generatedFrom.pnpmLockSha256}\`
- Cargo lock SHA-256: \`${dependencies.generatedFrom.cargoLockSha256}\`
- Unknown licenses: \`${dependencies.summary.unknown}\`
- Forbidden licenses: \`${dependencies.summary.forbidden}\`
- Missing required metadata: \`${dependencies.summary.missing}\`

## Live2D Cubism SDK for Web

- SDK version: \`${upstream.sdkVersion}\`
- Upstream archive: ${upstream.sdkUrl}
- Upstream archive SHA-256: \`${upstream.sdkArchiveSha256}\`
- Framework tag: \`${upstream.frameworkTag}\`
- Framework commit: \`${upstream.frameworkTagCommit}\`
- Cubism Core version: \`${upstream.coreVersion}\`
- Cubism Core runtime SHA-256: \`${upstream.coreSha256}\`
- Cubism Core declaration SHA-256: \`${upstream.coreDeclarationSha256}\`

## Bundled Hiyori model

- Pack ID: \`${hiyori.packId}\`
- Bundled version: \`${hiyori.bundledVersion}\`
- Illustration: ${hiyori.provenance.illustration}
- Modeling: ${hiyori.provenance.modeling}
- Source notice SHA-256: \`${hiyori.provenance.noticeSha256}\`

## Packaged source notices and provenance

| Component | Packaged file | SHA-256 | Canonical repository source |
| --- | --- | --- | --- |
${rows}
`
}

export function syncReleaseNotices(projectRoot) {
  const destination = getReleaseNoticeRoot(projectRoot)
  const staging = `${destination}.staging-${process.pid}`
  rmSync(staging, { force: true, recursive: true })
  mkdirSync(staging, { recursive: true })

  try {
    for (const entry of getReleaseNoticeEntries(projectRoot).filter(
      (candidate) => candidate.copyToLegal !== false,
    )) {
      const target = path.join(staging, entry.destination)
      mkdirSync(path.dirname(target), { recursive: true })
      copyFileSync(entry.sourcePath, target)
    }
    writeFileSync(
      path.join(staging, RELEASE_NOTICE_INDEX),
      buildReleaseNoticeIndex(projectRoot),
    )
    rmSync(destination, { force: true, recursive: true })
    renameSync(staging, destination)
  } catch (error) {
    rmSync(staging, { force: true, recursive: true })
    throw error
  }

  return verifyReleaseNotices(projectRoot)
}

export function verifyReleaseNotices(
  projectRoot,
  legalRoot = getReleaseNoticeRoot(projectRoot),
) {
  const entries = getReleaseNoticeEntries(projectRoot)
  const legalEntries = entries.filter((entry) => entry.copyToLegal !== false)
  assertExactFiles(
    legalRoot,
    [RELEASE_NOTICE_INDEX, ...legalEntries.map((entry) => entry.destination)],
    "packaged third-party notices",
  )

  for (const entry of entries) {
    const source = readFileSync(entry.sourcePath)
    const packaged = readFileSync(path.join(legalRoot, entry.destination))
    if (!source.equals(packaged)) {
      fail(
        `packaged third-party notice differs from canonical source: ${entry.destination}`,
      )
    }
  }

  const expectedIndex = buildReleaseNoticeIndex(projectRoot)
  const actualIndex = readFileSync(
    path.join(legalRoot, RELEASE_NOTICE_INDEX),
    "utf8",
  )
  if (actualIndex !== expectedIndex) {
    fail("packaged THIRD-PARTY-NOTICES.md has provenance or hash drift")
  }

  return {
    files: entries.length + 1,
    root: legalRoot,
  }
}

export function createReleaseNoticeAssetMap(projectRoot) {
  const legalRoot = getReleaseNoticeRoot(projectRoot)
  verifyReleaseNotices(projectRoot, legalRoot)
  return new Map([
    [RELEASE_NOTICE_INDEX, path.join(legalRoot, RELEASE_NOTICE_INDEX)],
    ...getReleaseNoticeEntries(projectRoot)
      .filter((entry) => entry.copyToLegal !== false)
      .map((entry) => [
        entry.destination,
        path.join(legalRoot, entry.destination),
      ]),
  ])
}
