import type { SupportedLocale } from "@/features/localization"

const en = {
  workspaces: "Workspaces",
  filterWorkspaces: "Filter workspaces",
  addProject: "Add project",
  addWorkspace: "Add workspace",
  settings: "Settings",
  appMark: "Coding Wife workspace",
  workspaceActions: "Workspace actions",
  dismiss: "Dismiss",
  switchWorkspace: "Switch workspace",
  repository: "Repository",
  branch: "Branch",
  active: "Active",
  noMatches: "No workspaces match this filter.",
  clearFilter: "Clear filter",
  lifecycle: {
    done: "Done",
    in_review: "In review",
    in_progress: "In progress",
    backlog: "Backlog",
    canceled: "Canceled",
  },
  attention: {
    needs_answer: "Needs answer",
    test_failed: "Test failed",
    high_risk: "High risk",
  },
  tabs: {
    chat: "Chat",
    commit: "Commit",
    context: "Context",
    settings: "Settings",
  },
  connection: {
    checking: "Checking runtime",
    preview: "Preview only",
    offline: "Offline",
    ready: "Ready",
  },
  previewNoticeTitle: "Design preview",
  previewNotice:
    "Codex, Git, Live2D, and local history are not connected. Controls remain available for UI verification, but no repository operation is reported as complete.",
  runtimeErrorTitle: "The local runtime could not be reached",
  runtimeErrorDescription:
    "Your draft and local view state are preserved. Retry the runtime check or review Diagnostics.",
  retry: "Retry",
  diagnostics: "Diagnostics",
  timelineTitle: "Activity",
  timelineDescription: "Structured, redacted workspace events",
  previewBadge: "Reference preview",
  tool: "Tool",
  completed: "Completed",
  failed: "Failed",
  expandDetails: "Show safe details",
  collapseDetails: "Hide details",
  assistantPreview:
    "The desktop work surface is ready for integration. This preview demonstrates the event hierarchy without claiming a live Codex session.",
  verificationPreview:
    "Frontend checks can be presented as named evidence with a terminal result, duration, and a link to the corresponding checkpoint.",
  errorTitle: "Connection required",
  errorBody:
    "Sending remains blocked until the local Codex preflight succeeds. The draft is kept unchanged.",
  decisionTitle: "Review boundary preview",
  decisionQuestion: "How should the next work unit be scoped?",
  decisionWhy:
    "A smaller unit keeps the evidence and recovery point reviewable before implementation continues.",
  decisionOptionSmall: "Keep one reviewable unit",
  decisionOptionSmallImpact:
    "Complete one bounded change and verify it before continuing.",
  decisionOptionHold: "Hold for review",
  decisionOptionHoldImpact: "Pause without changing source or Git state.",
  decisionRecommendation: "Recommended: one reviewable unit",
  decisionUncertainty: "No live decision request is active in preview mode.",
  answerPreview: "Save preview answer",
  answerSaved: "Preview answer saved locally",
  composerPlaceholder: "Ask Codex to plan, build, explain, or fix anything…",
  composerHint:
    "Attach files or images · paste a screenshot · drag files here · use @ to reference context",
  add: "Add",
  context: "Context",
  filesFolders: "Files & folders",
  gitDiff: "Git diff",
  terminalOutput: "Terminal output",
  model: "GPT-5.6 Sol",
  fast: "Fast",
  max: "Max",
  send: "Send",
  stop: "Stop",
  commandSend: "⌘↵ send",
  removeAttachment: "Remove attachment",
  attachmentRejected: "Files over 25 MiB remain visible but cannot be sent.",
  sendUnavailable: "Codex is not connected. Your draft will be preserved.",
  sendEmpty: "Enter an instruction or attach valid context.",
  sendBusy: "Wait for the current turn to finish or stop it.",
  pickerUnavailable:
    "The native operation is not connected in this preview. No local project state changed.",
  contextUnavailable:
    "Context capture requires the native workspace adapter. The draft was not changed.",
  character: {
    rendererPending: "Live2D renderer pending",
    rendererDescription:
      "The verified CharacterStage renderer mounts here. No substitute image is shown.",
    state: "Companion state",
    disconnected: "Disconnected",
    muted: "Muted",
    unmuted: "Audio available",
    mute: "Mute companion",
    unmute: "Unmute companion",
  },
  commit: {
    title: "Session evidence",
    description:
      "Checkpoint evidence appears here only after Scope, Ownership, Verification, and Risk have terminal results.",
    emptyTitle: "No persisted checkpoint evidence",
    emptyDescription:
      "The preview transport has not created a Git object or review pack.",
    backToChat: "Back to Chat",
    gateSummary: "Checkpoint gates",
    unavailable: "Unavailable",
    gates: ["Scope", "Ownership", "Verification", "Risk"],
    listTitle: "Checkpoints",
    noCheckpoint: "No checkpoint",
    detailTitle: "Evidence detail",
    detailBody:
      "Connect local history and Git services to inspect sanitized diffs, decisions, failed attempts, risks, and recovery actions.",
  },
  contextView: {
    title: "Workspace context",
    description:
      "Project instructions and companion presentation remain separate. Changes apply from the next turn.",
    projectTitle: "Project context",
    projectDescription: "Goals, constraints, and definition of done for Codex.",
    characterTitle: "Character context",
    characterDescription:
      "Tone and presentation preferences that cannot override technical policy.",
    goal: "Goal",
    constraints: "Constraints",
    definition: "Definition of done",
    displayName: "Display name",
    tone: "Tone",
    prohibited: "Prohibited expressions",
    saveProject: "Save project draft",
    saveCharacter: "Save character draft",
    localOnly: "Held locally until the workspace history service is connected.",
    version: "Version",
    nextTurn: "Applies from the next turn",
  },
  settingsView: {
    title: "Settings & diagnostics",
    description:
      "Local preferences, safety boundaries, and integration readiness.",
    sections: {
      general: "General",
      project_context: "Project context",
      character_context: "Character context",
      companion: "Companion",
      audio: "Audio",
      support: "Support",
      diagnostics: "Diagnostics",
      history: "History & privacy",
    },
    generalTitle: "General",
    language: "Language",
    languageDescription:
      "Changes app-owned copy immediately and persists when the locale store accepts it.",
    languageSaveError:
      "The language could not be saved. The previous language is unchanged.",
    motion: "Reduced motion",
    motionDescription:
      "System preference always takes precedence when reduction is requested.",
    system: "System",
    reduce: "Reduce",
    allow: "Allow",
    appVersion: "App version",
    resetUi: "Reset UI state",
    resetUiDescription:
      "Resets filters and local view selections. Repository and history data are not changed.",
    companionTitle: "Companion",
    bundledModel: "Bundled model",
    bundledModelValue: "Hiyori · awaiting verified renderer",
    importModel: "Import model",
    hideCharacter: "Hide character",
    hideCharacterDescription:
      "Stops the visual stage while keeping the semantic text state.",
    audioTitle: "Audio",
    tts: "Enable TTS",
    ttsDescription:
      "Off by default. No external request is made by this UI preview.",
    mute: "Mute",
    rate: "Speech rate",
    supportTitle: "Support",
    supportGlobal: "Enable isolated support",
    supportDescription:
      "Requires a proven ephemeral, tool-free runtime. It remains off in preview mode.",
    presence: "Presence narration",
    reviewer: "Checkpoint reviewer",
    diagnosticsTitle: "Diagnostics",
    recheck: "Recheck runtime",
    runtimeMode: "Runtime mode",
    platform: "Platform",
    integrations: "Integration readiness",
    notConfigured: "Not configured",
    historyTitle: "History & privacy",
    stored: "Stored locally",
    storedBody:
      "Workspace metadata, normalized events, drafts, context, and evidence packs.",
    neverStored: "Never stored",
    neverStoredBody:
      "Raw reasoning, generated audio, support prompt/response, and raw secrets.",
    deleteHistory: "Delete workspace history",
    deleteDisabled: "No connected history service; nothing was deleted.",
    localPreview:
      "Preview preference · not persisted to the native settings service",
  },
  createWorkspace: {
    title: "Create workspace",
    description:
      "Adds a local Backlog entry. Repository operations require the native adapter.",
    name: "Workspace name",
    goal: "Goal",
    cancel: "Cancel",
    create: "Create",
  },
  compactSidebar: "Open workspace navigation",
}

const ja: typeof en = {
  ...en,
  workspaces: "ワークスペース",
  filterWorkspaces: "ワークスペースを絞り込む",
  addProject: "プロジェクトを追加",
  addWorkspace: "ワークスペースを追加",
  settings: "設定",
  appMark: "Coding Wifeワークスペース",
  workspaceActions: "ワークスペース操作",
  dismiss: "閉じる",
  switchWorkspace: "ワークスペースを切り替える",
  repository: "リポジトリ",
  branch: "ブランチ",
  active: "選択中",
  noMatches: "条件に一致するワークスペースはありません。",
  clearFilter: "フィルターを解除",
  lifecycle: {
    done: "完了",
    in_review: "レビュー可能",
    in_progress: "実行中",
    backlog: "未着手",
    canceled: "中止",
  },
  attention: {
    needs_answer: "回答待ち",
    test_failed: "テスト失敗",
    high_risk: "高リスク",
  },
  tabs: {
    chat: "チャット",
    commit: "コミット",
    context: "コンテキスト",
    settings: "設定",
  },
  connection: {
    checking: "実行環境を確認中",
    preview: "プレビューのみ",
    offline: "オフライン",
    ready: "準備完了",
  },
  previewNoticeTitle: "デザインプレビュー",
  previewNotice:
    "Codex、Git、Live2D、ローカル履歴は未接続です。UI確認用の操作は利用できますが、リポジトリ操作を完了として表示しません。",
  runtimeErrorTitle: "ローカル実行環境へ接続できませんでした",
  runtimeErrorDescription:
    "下書きとローカル表示状態は保持されています。実行環境を再確認するか、診断を確認してください。",
  retry: "再試行",
  diagnostics: "診断",
  timelineTitle: "アクティビティ",
  timelineDescription: "構造化・秘匿化されたワークスペースイベント",
  previewBadge: "参照プレビュー",
  tool: "ツール",
  completed: "完了",
  failed: "失敗",
  expandDetails: "安全な詳細を表示",
  collapseDetails: "詳細を閉じる",
  assistantPreview:
    "デスクトップ作業面は統合可能な状態です。このプレビューは実Codexセッションの成功を主張せず、イベント階層だけを示します。",
  verificationPreview:
    "フロントエンドの検証は、名称、終了結果、所要時間、対応checkpointへの導線を持つ証拠として提示できます。",
  errorTitle: "接続が必要です",
  errorBody:
    "ローカルCodexの事前診断が成功するまで送信は無効です。下書きは変更されません。",
  decisionTitle: "レビュー境界のプレビュー",
  decisionQuestion: "次の作業単位をどの範囲にしますか？",
  decisionWhy:
    "実装を続ける前に小さく区切ると、証拠と復元地点をレビュー可能に保てます。",
  decisionOptionSmall: "レビュー可能な1単位にする",
  decisionOptionSmallImpact:
    "一つの限定された変更を完了・検証してから続けます。",
  decisionOptionHold: "レビューまで保留する",
  decisionOptionHoldImpact: "sourceやGit状態を変更せず待機します。",
  decisionRecommendation: "推奨: レビュー可能な1単位",
  decisionUncertainty: "プレビューモードでは実際の判断要求は発生していません。",
  answerPreview: "プレビュー回答を保存",
  answerSaved: "プレビュー回答をローカルに保存しました",
  composerPlaceholder: "Codexに計画、実装、説明、修正を依頼…",
  composerHint:
    "ファイルや画像を添付 · スクリーンショットを貼り付け · ファイルをドロップ · @でコンテキストを参照",
  add: "追加",
  context: "コンテキスト",
  filesFolders: "ファイルとフォルダー",
  gitDiff: "Git差分",
  terminalOutput: "ターミナル出力",
  model: "GPT-5.6 Sol",
  fast: "高速",
  max: "最大",
  send: "送信",
  stop: "停止",
  commandSend: "⌘↵ 送信",
  removeAttachment: "添付を削除",
  attachmentRejected:
    "25 MiBを超えるファイルは表示を残しますが送信できません。",
  sendUnavailable: "Codexは未接続です。下書きは保持されます。",
  sendEmpty: "指示を入力するか、有効なコンテキストを追加してください。",
  sendBusy: "現在のturnを完了するか、停止してください。",
  pickerUnavailable:
    "このプレビューではnative操作が未接続です。ローカルproject状態は変更していません。",
  contextUnavailable:
    "コンテキスト取得にはnative workspace adapterが必要です。下書きは変更していません。",
  character: {
    rendererPending: "Live2D renderer待機中",
    rendererDescription:
      "検証済みCharacterStage rendererをここへ接続します。代替の人物画像は表示していません。",
    state: "コンパニオン状態",
    disconnected: "切断中",
    muted: "ミュート中",
    unmuted: "音声利用可能",
    mute: "コンパニオンをミュート",
    unmute: "コンパニオンのミュートを解除",
  },
  commit: {
    title: "セッション証拠",
    description:
      "Scope、Ownership、Verification、Riskがterminalになった後だけcheckpoint証拠を表示します。",
    emptyTitle: "永続化済みcheckpoint証拠はありません",
    emptyDescription:
      "プレビューtransportはGit objectやreview packを作成していません。",
    backToChat: "チャットへ戻る",
    gateSummary: "Checkpoint gate",
    unavailable: "利用不可",
    gates: ["Scope", "Ownership", "Verification", "Risk"],
    listTitle: "チェックポイント",
    noCheckpoint: "Checkpointなし",
    detailTitle: "証拠詳細",
    detailBody:
      "ローカル履歴とGit serviceを接続すると、秘匿化された差分、判断、失敗、リスク、復元操作を確認できます。",
  },
  contextView: {
    title: "ワークスペースコンテキスト",
    description:
      "project指示とcompanion表現を分離します。変更は次のturnから適用します。",
    projectTitle: "プロジェクトコンテキスト",
    projectDescription: "Codexへ渡す目標、制約、完了条件です。",
    characterTitle: "キャラクターコンテキスト",
    characterDescription: "技術policyを上書きできない口調と表現設定です。",
    goal: "目標",
    constraints: "制約",
    definition: "完了条件",
    displayName: "表示名",
    tone: "口調",
    prohibited: "禁止表現",
    saveProject: "Project下書きを保存",
    saveCharacter: "Character下書きを保存",
    localOnly:
      "workspace履歴service接続まではローカル表示状態だけに保持します。",
    version: "バージョン",
    nextTurn: "次のturnから適用",
  },
  settingsView: {
    title: "設定・診断",
    description: "ローカル設定、安全境界、連携準備状況を確認します。",
    sections: {
      general: "一般",
      project_context: "プロジェクトコンテキスト",
      character_context: "キャラクターコンテキスト",
      companion: "コンパニオン",
      audio: "音声",
      support: "支援",
      diagnostics: "診断",
      history: "履歴とプライバシー",
    },
    generalTitle: "一般",
    language: "言語",
    languageDescription:
      "アプリ管理文言を即時に切り替え、locale storeが受理した場合だけ永続化します。",
    languageSaveError:
      "言語を保存できませんでした。以前の言語を維持しています。",
    motion: "動きを減らす",
    motionDescription: "OSが動きの削減を要求している場合は常に優先します。",
    system: "システム",
    reduce: "減らす",
    allow: "許可",
    appVersion: "アプリバージョン",
    resetUi: "UI状態をリセット",
    resetUiDescription:
      "filterとローカル選択だけを戻します。repositoryと履歴dataは変更しません。",
    companionTitle: "コンパニオン",
    bundledModel: "同梱モデル",
    bundledModelValue: "Hiyori · 検証済みrenderer待機中",
    importModel: "モデルをimport",
    hideCharacter: "キャラクターを非表示",
    hideCharacterDescription:
      "visual stageを停止し、semantic text状態は残します。",
    audioTitle: "音声",
    tts: "TTSを有効化",
    ttsDescription:
      "初期値はoffです。このUI previewから外部requestは行いません。",
    mute: "ミュート",
    rate: "読み上げ速度",
    supportTitle: "支援",
    supportGlobal: "分離支援を有効化",
    supportDescription:
      "toolなしのephemeral runtimeを証明する必要があるため、previewではoffを維持します。",
    presence: "状況実況",
    reviewer: "Checkpoint reviewer",
    diagnosticsTitle: "診断",
    recheck: "実行環境を再確認",
    runtimeMode: "実行モード",
    platform: "プラットフォーム",
    integrations: "連携準備状況",
    notConfigured: "未構成",
    historyTitle: "履歴とプライバシー",
    stored: "ローカルに保存",
    storedBody:
      "workspace metadata、正規化event、下書き、context、evidence pack。",
    neverStored: "保存しない",
    neverStoredBody:
      "raw reasoning、生成音声、support prompt/response、raw secret。",
    deleteHistory: "ワークスペース履歴を削除",
    deleteDisabled: "履歴serviceは未接続です。何も削除していません。",
    localPreview: "プレビュー設定 · native settings serviceには未保存",
  },
  createWorkspace: {
    title: "ワークスペースを作成",
    description:
      "ローカルのBacklog entryを追加します。repository操作にはnative adapterが必要です。",
    name: "ワークスペース名",
    goal: "目標",
    cancel: "キャンセル",
    create: "作成",
  },
  compactSidebar: "ワークスペースnavigationを開く",
}

export type WorkspaceCopy = typeof en

export function getWorkspaceCopy(locale: SupportedLocale): WorkspaceCopy {
  return locale === "ja" ? ja : en
}
