import type { SupportedLocale } from "@/features/localization"

const en = {
  workspaces: "Workspaces",
  filterWorkspaces: "Filter workspaces",
  addProject: "Add project",
  addWorkspace: "Add workspace",
  archiveWorkspace: "Archive workspace",
  settings: "Settings",
  appSettings: "App settings",
  repositoryBreadcrumb: "Repository location",
  workspaceActions: "Workspace actions",
  workspaceHealth: {
    ready: "Repository ready",
    missing: "Repository missing",
    changed: "Repository identity changed",
    unreadable: "Repository unreadable",
    read_only: "Repository is read-only",
    stale_branch: "Branch changed outside the app",
  },
  workspaceMenu: {
    cancel: "Cancel workspace",
    cancelDescription: "Stop work and keep its history for review.",
    repair: "Reselect repository…",
    repairDescription: "Choose the repository again to repair local access.",
    recheckRepository: "Recheck repository",
    recheckDescription:
      "Verify and use the branch and HEAD currently present on disk.",
    unregister: "Unregister project…",
    unregisterDescription: "Hide this project without deleting its history.",
    runningBlocked: "Unavailable while a turn is running.",
    cancelTitle: "Cancel this workspace?",
    cancelBody:
      "Its app lifecycle changes to Canceled. Source files, the worktree, Git refs, and history are kept.",
    cancelRunningBody:
      "The active turn must stop first. Its lifecycle changes to Canceled only after the exact turn is terminal and local cleanup finishes.",
    keepWorkspace: "Go back",
    confirmCancel: "Cancel workspace",
    stopAndCancel: "Stop and cancel",
    unregisterTitle: "Unregister this project?",
    unregisterBody:
      "All of this project's workspaces disappear from navigation. Source files, the worktree, Git refs, drafts, and history are not deleted.",
    continueUnregister: "Continue",
    unregisterFinalTitle: "Confirm project unregister",
    unregisterFinalBody:
      "This removes only the app's active project registration. You can register the repository again later to restore its preserved history.",
    confirmUnregister: "Unregister project",
    working: "Working…",
    error: {
      generic:
        "The workspace action could not be completed. No source or Git state was changed.",
      active:
        "The project is still running. Stop its active turn before unregistering or repairing it.",
      unavailable: "This action is not available in the current runtime.",
      conflict:
        "The workspace changed in another operation. Refresh it and try again.",
      rootInUse: "That repository is already registered to another project.",
      draft:
        "The latest draft could not be saved, so the project was not unregistered.",
    },
  },
  archiveDialog: {
    title: "Archive this workspace?",
    body: (workspace: string) =>
      `The Git worktree for ${workspace} and its app history will be removed. The project repository and branch are kept.`,
    cancel: "Keep workspace",
    confirm: "Archive workspace",
    working: "Archiving…",
  },
  workspaceSwitch: {
    title: "Stop and switch workspaces?",
    description:
      "The current workspace stays active until its exact turn is interrupted, reaches a terminal state, and finishes local cleanup.",
    from: "Current workspace",
    to: "Switch to",
    goBack: "Go back",
    confirm: "Stop and switch",
    stopping: "Stopping and switching…",
    failed:
      "The turn could not be stopped and cleaned up. The current workspace remains active; no draft or selection was changed.",
  },
  dismiss: "Dismiss",
  switchWorkspace: "Switch workspace",
  repository: "Repository",
  branch: "Branch",
  active: "Active",
  noMatches: "No workspaces match this filter.",
  loadingWorkspacesTitle: "Restoring workspace history",
  loadingWorkspacesDescription:
    "Checking local workspace records before enabling changes.",
  workspaceLoadFailedTitle: "Workspace history could not be restored",
  workspaceLoadFailedDescription:
    "Demo data was not substituted. Retry the local history check to continue safely.",
  clearFilter: "Clear filter",
  lifecycle: {
    done: "Done",
    in_review: "In review",
    in_progress: "In progress",
    backlog: "Backlog",
    canceled: "Canceled",
  },
  attention: {
    needs_answer: "Needs answer",
    approval_required: "Approval required",
    test_failed: "Test failed",
    high_risk: "High risk",
  },
  tabs: {
    chat: "Chat",
    commit: "Commit",
    settings: "Settings",
  },
  connection: {
    checking: "Checking runtime",
    preview: "Preview only",
    offline: "Offline",
    ready: "Ready",
  },
  previewNoticeTitle: "Design preview",
  previewNotice:
    "Codex, Git, and local history are not connected. The bundled Live2D companion reports its renderer state separately.",
  previewNoticeWithHistory:
    "Codex and Git are not connected. Local workspace history is persisted and available.",
  previewNoticeWithEphemeralHistory:
    "Codex and Git are not connected. Demo workspace activity is kept in memory and resets when this preview restarts.",
  interactiveDemoNotice:
    "The deterministic Codex App Server demo is connected. Git remains disconnected; activity stays in memory and resets when this preview restarts.",
  runtimeErrorTitle: "The local runtime could not be reached",
  runtimeErrorDescription:
    "Your draft and local view state are preserved. Retry the runtime check or review Diagnostics.",
  retry: "Retry",
  diagnostics: "Diagnostics",
  timelineTitle: "Activity",
  timelineDescription: "Structured, redacted workspace events",
  lastSummaryTitle: "Last session summary",
  lastSummaryDescription:
    "Restored from this workspace's redacted local history.",
  previewBadge: "Reference preview",
  persistedBadge: "Persisted locally",
  ephemeralHistoryBadge: "Demo memory",
  historyUnavailable: "History requires recovery",
  timelineEmptyTitle: "No persisted activity yet",
  timelineEmptyBody:
    "Start the first turn or inspect project diagnostics before continuing.",
  timelineEvent: {
    kind: {
      thread: "Codex session",
      turn: "Turn",
      user: "You",
      assistant: "Codex",
      plan: "Plan updated",
      tool: "Tool run",
      file: "File change",
      diff: "Diff updated",
      decision: "Decision",
      approval: "Approval",
      request_resolved: "Response recorded",
      error: "Action failed",
      completion: "Turn completed",
      status: "Activity",
    },
    history: "Recorded event",
    running: "Running",
    streaming: "Responding",
    interrupted: "Interrupted",
    effort: "Effort",
    attachments: "attachments",
    decisionRequired: "Your decision is needed",
    approvalRequired: "Approval required",
    responseNeeded: "Codex is waiting for a bounded response.",
    waitingForYou: "Waiting for you",
    responded: "Responded",
    operation: "Operation",
    target: "Target",
    effect: "Effect",
    scope: "Scope",
    risk: "Risk",
    reversibility: "Reversibility",
    recommendation: "Recommendation",
    uncertainty: "Uncertainty",
    evidence: "Evidence",
    noRecommendation: "No recommendation",
    decisionEffect: {
      execute_command: "Run the command",
      apply_file_change: "Apply the file change",
      grant_permissions: "Grant the requested permissions",
      continue_turn: "Continue the active turn",
    },
    scopeValue: {
      command: "This command",
      turn: "This turn",
    },
    riskValue: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    reversibilityValue: {
      reversible: "Reversible",
      partially_reversible: "Partially reversible",
      not_reversible: "Not reversible",
      unknown: "Unknown",
    },
    uncertaintyValue: {
      none: "None",
      limited_context: "Limited context",
      unknown_effects: "Unknown effects",
    },
    answer: "Send answer",
    submitting: "Sending…",
    other: "Other",
    otherDescription: "Provide a different bounded answer.",
    otherAnswer: "Other answer",
    otherPlaceholder: "Enter 1–2,000 characters",
    hold: "Hold decision",
    held: "Held. No response was sent; this turn is still waiting.",
    interrupt: "Interrupt turn",
    interruptDialogTitle: "Interrupt this turn?",
    interruptDialogDescription:
      "Codex will stop the active turn. Completed workspace changes remain available for review.",
    interruptDialogCancel: "Keep running",
    interruptDialogConfirm: "Interrupt turn",
    interrupting: "Interrupting…",
    interruptFailed:
      "The turn could not be interrupted. It may still be running; try again.",
    approvalDecision: {
      approve_once: "Approve once",
      reject: "Reject",
      stop: "Stop turn",
    },
    copyDetails: "Copy safe details",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Copy failed",
    latest: "Latest",
    newUpdates: "New updates",
  },
  tool: "Tool",
  completed: "Completed",
  failed: "Failed",
  expandDetails: "Show safe details",
  collapseDetails: "Hide details",
  assistantPreview:
    "The desktop work surface is ready for integration. This preview demonstrates the event hierarchy without claiming a live Codex session.",
  verificationPreview:
    "Frontend checks can be presented as named evidence with a terminal result, duration, and a link to the corresponding commit.",
  errorTitle: "Connection required",
  errorBody:
    "Sending remains blocked until the local Codex preflight succeeds. The draft is kept unchanged.",
  decisionTitle: "Review boundary preview",
  decisionQuestion: "How should the next work unit be scoped?",
  decisionWhy:
    "A smaller unit keeps the evidence and main-session commit reviewable before implementation continues.",
  decisionOptionSmall: "Keep one reviewable unit",
  decisionOptionSmallImpact:
    "Complete one bounded change and verify it before continuing.",
  decisionOptionHold: "Hold for review",
  decisionOptionHoldImpact: "Pause without changing source or Git state.",
  decisionRecommendation: "Recommended: one reviewable unit",
  decisionUncertainty: "No live decision request is active in preview mode.",
  answerPreview: "Save preview answer",
  answerSaved: "Preview answer saved locally",
  composerPlaceholder: "Ask Codex to plan, build, explain, or fix anything…",
  composerHint:
    "Attach files or images · paste a screenshot · drag files here · use @ to reference context",
  add: "Add",
  context: "Context",
  filesFolders: "Files & folders",
  gitDiff: "Git diff",
  terminalOutput: "Terminal output",
  model: "GPT-5.6 Sol",
  fixedModel: "fixed model",
  draftItems: "Draft items",
  reasoningEffort: "Reasoning effort",
  effortAvailability: {
    none: "No reasoning effort is currently available.",
    fast: "Fast reasoning is not available in this runtime.",
    max: "Maximum reasoning is not available in this runtime.",
  },
  fast: "Fast",
  max: "Max",
  send: "Send",
  stop: "Stop",
  commandSend: "⌘↵ send",
  removeAttachment: "Remove attachment",
  attachmentRejected: "Files over 25 MiB remain visible but cannot be sent.",
  sendUnavailable: "Codex is not connected. Your draft will be preserved.",
  sendEmpty: "Enter an instruction or attach valid context.",
  sendBusy: "Wait for the current turn to finish or stop it.",
  pickerUnavailable:
    "The native operation is not connected in this preview. No local project state changed.",
  contextUnavailable:
    "Context capture requires the native workspace adapter. The draft was not changed.",
  character: {
    rendererPending: "Starting Live2D renderer",
    rendererDescription:
      "The app-owned Live2D renderer reports verified status and safe fallback details here.",
    externalRenderer: "External renderer · status unavailable",
    retryRenderer: "Retry Live2D",
    state: "Companion state",
    disconnected: "Disconnected",
    semanticState: {
      idle: "Idle",
      thinking: "Thinking",
      acting: "Acting",
      waiting_for_user: "Waiting for you",
      reviewing: "Reviewing",
      error: "Error",
      completed: "Completed",
      disconnected: "Disconnected",
    },
    muted: "Muted",
    unmuted: "Audio available",
    mute: "Mute companion",
    unmute: "Unmute companion",
  },
  contextView: {
    title: "Project context",
    description:
      "Project-specific instructions for Codex. Changes apply from the next turn.",
    projectTitle: "Project context",
    projectDescription: "Goals, constraints, and definition of done for Codex.",
    characterTitle: "Character context",
    characterDescription:
      "Tone and presentation preferences that cannot override technical policy.",
    goal: "Goal",
    constraints: "Constraints",
    definition: "Definition of done",
    displayName: "Display name",
    tone: "Tone",
    prohibited: "Prohibited expressions",
    saveProject: "Save project context",
    saveCharacter: "Save character draft",
    localOnly: "Held locally until the project context service is connected.",
    version: "Version",
    nextTurn: "Applies from the next turn",
    conflictTitle: "A newer version is available",
    conflictVersions:
      "Your draft started at v{local}; the saved context is v{remote}.",
    changedFields: "Different fields:",
    reloadCurrent: "Reload saved version",
    saveError: "Context could not be saved",
    saveErrorDescription:
      "Your draft is still here. Review the details and try again.",
    errors: {
      required: "Enter a value before saving.",
      text: "This value exceeds its limit or contains unsupported control characters.",
      items: "Review the item count and per-item character limits.",
      technicalReference:
        "Use a normalized project-relative path or supported document reference.",
      policy:
        "Character presentation cannot change technical or safety policy.",
      total: "This context exceeds the total character limit.",
      referenceBoundary:
        "Technical references must resolve inside the registered project.",
      referenceMissing:
        "A saved technical reference is no longer available. Review and save it again.",
      referenceChanged:
        "A saved technical reference now resolves to a different target. Review and save it again.",
    },
    savedNextTurn: "Saved. This version will be used from the next turn.",
    loading: "Loading project context",
    unsaved: "Unsaved",
    technicalReferences: "Technical references",
    onePerLine: "One item per line",
    referencesDescription:
      "Project-relative paths only. Policy files and paths outside this project are rejected.",
    userNotes: "User notes",
    toneNotes: "Tone notes",
    speechDensity: "Speech density",
    concise: "Concise",
    warm: "Warm",
    neutral: "Neutral",
    quiet: "Quiet",
    keyEvents: "Key events",
    detailed: "Detailed",
    behavior: "Behavior",
    policyBoundary:
      "Presentation preferences cannot override technical or safety policy",
    total: "{count} / {maximum} characters",
    runningTurnUnaffected:
      "The current turn keeps its captured version; changes affect the next turn.",
    discard: "Discard draft",
    saving: "Saving…",
  },
  settingsView: {
    appTitle: "App settings",
    appDescription:
      "Character, companion, preferences, and diagnostics shared by every project.",
    projectTitle: "Project settings",
    projectDescription: (project: string) => `Settings for ${project}.`,
    workspaceTitle: "Workspace settings",
    workspaceDescription: (workspace: string) =>
      `History and privacy for ${workspace}.`,
    backToWorkspace: "Back to workspace",
    backToProjects: "Back to projects",
    sections: {
      general: "General",
      projects: "Projects",
      project_context: "Project context",
      character_context: "Character context",
      companion: "Companion",
      audio: "Audio",
      diagnostics: "Diagnostics",
      history: "History & privacy",
    },
    generalTitle: "General",
    projectsTitle: "Registered projects",
    projectsDescription:
      "Open a project to manage the context shared by its workspaces. Unregistering changes only this app.",
    projectContextDescription: (workspaceCount: string) =>
      `Context shared by this project's ${workspaceCount}.`,
    noProjectsTitle: "No registered projects",
    noProjectsDescription:
      "Use the folder button in the sidebar to register a Git repository.",
    workspaceCount: (count: number) =>
      `${count.toLocaleString()} ${count === 1 ? "workspace" : "workspaces"}`,
    unregisterProject: "Unregister",
    unregisterProjectTitle: "Unregister this project?",
    unregisterProjectBody: (project: string) =>
      `${project} will disappear from this app. Its repository, worktrees, branches, and files remain on disk.`,
    keepProject: "Keep project",
    confirmUnregisterProject: "Unregister project",
    unregisteringProject: "Unregistering…",
    language: "Language",
    languageDescription:
      "Applies to all app-owned copy as soon as the preference store accepts the change.",
    languageSaveError:
      "The language could not be saved. The previous language is unchanged.",
    preferenceStatusNative: "Native preferences",
    preferenceStatusDemo: "Demo memory · resets when this preview restarts",
    preferenceVersion: "Version",
    preferenceSaving: "Saving preferences…",
    preferenceRecoveryTitle: "Preferences need recovery",
    preferenceRecoveryBody:
      "Safe defaults are active. The unreadable value was not shown or applied.",
    preferenceErrorTitle: "Preferences were not saved",
    preferenceErrorBody:
      "The last durable preferences remain active. Retry the change or reset only the preference record.",
    preferenceSafeCode: "Safe code",
    motion: "Reduced motion",
    motionDescription:
      "System preference always takes precedence when reduction is requested.",
    system: "System",
    reduce: "Reduce",
    allow: "Allow",
    characterVisibility: "Character visibility",
    characterVisibilityDescription:
      "Hiding stops the canvas and GPU animation across every workspace while keeping the text state.",
    characterVisible: "Character visible",
    appVersion: "App version",
    resetPreferences: "Reset preferences",
    resetPreferencesDescription:
      "Returns language to the OS default, motion to System, and the character to Visible. Workspaces, history, Context, model library, Git, and audio settings are unchanged.",
    resetPreferencesConfirmTitle: "Reset app preferences?",
    resetPreferencesConfirmBody:
      "Only AppPreferencesV1 will be replaced. Workspaces, history, Context, the character model library, Git state, and audio settings stay unchanged.",
    resetPreferencesCancel: "Cancel",
    resetPreferencesConfirm: "Reset preferences",
    resetPreferencesInProgress: "Resetting…",
    resetUi: "Reset UI state",
    resetUiDescription:
      "Resets filters and local view selections. Repository and history data are not changed.",
    companionTitle: "Companion",
    bundledModel: "Model",
    bundledModelValue: "Hiyori",
    renderer: "Renderer",
    builtinRenderer: "App Live2D",
    externalRenderer: "External renderer",
    bundledVersion: "Model version",
    provenance: "Provenance",
    illustrationCredit: "Illustration",
    modelingCredit: "Modeling",
    noticeHash: "Notice SHA-256",
    phase: "Phase",
    fallback: "Fallback",
    motionPolicy: "Motion policy",
    audioState: "Audio",
    lastError: "Last safe error",
    noRecordedError: "None recorded",
    unknown: "Unknown",
    characterPhases: {
      idle: "Idle",
      loading: "Loading",
      ready: "Ready",
      recovering: "Recovering",
      error: "Error",
      disposed: "Stopped",
      hidden: "Hidden",
      unknown: "Unknown",
    },
    characterFallbacks: {
      animated: "Animated",
      reduced: "Reduced",
      static: "Static preview",
      text_only: "Text only",
      unknown: "Unknown",
    },
    characterPolicies: {
      animated: "Animated",
      reduced: "Reduced",
      hidden: "Hidden",
      unknown: "Unknown",
    },
    live2dStatus: "Live2D",
    live2dLoading: "Loading",
    live2dReady: "Ready",
    live2dRecovering: "Recovering",
    live2dDegraded: "Degraded",
    live2dError: "Error",
    live2dHidden: "Hidden",
    live2dUnknown: "Unknown",
    characterErrorIntro:
      "The companion fell back safely. Workspace controls remain available.",
    retryCharacter: "Retry Live2D",
    importModel: "Import model",
    hideCharacter: "Hide character",
    hideCharacterDescription:
      "Stops the visual stage while keeping the semantic text state.",
    audioTitle: "Audio",
    tts: "Enable TTS",
    ttsDescription:
      "Off by default. No external request is made by this UI preview.",
    mute: "Mute",
    rate: "Speech rate",
    diagnosticsTitle: "Diagnostics",
    recheck: "Recheck runtime",
    runtimeMode: "Runtime mode",
    platform: "Platform",
    integrations: "Integration readiness",
    notConfigured: "Not configured",
    localHistory: "Local history",
    historyReadOnly: "Read only",
    historyEphemeral: "Demo memory",
    historyTitle: "History & privacy",
    stored: "Stored locally",
    storedBody:
      "Workspace metadata, normalized events, drafts, context, and evidence packs.",
    storedEphemeral: "Stored in demo memory",
    storedEphemeralBody:
      "Workspace metadata, activity, drafts, context, and evidence exist only for this preview. Reloading restores the bundled demo.",
    neverStored: "Never stored",
    neverStoredBody:
      "Raw reasoning, generated audio, commit explanation input/output, and raw secrets.",
    deleteHistory: "Delete workspace history",
    deleteDisabled: "No connected history service; nothing was deleted.",
    deleteReady:
      "Deletes this workspace's app metadata and events. Repository files, commits, and branches are never changed.",
    deleteConfirmTitle: "Delete this workspace history?",
    deleteConfirmBody:
      "This removes local app history for the selected workspace only. This action cannot be undone.",
    deleteCancel: "Cancel",
    deleteConfirm: "Delete history",
    deleteInProgress: "Deleting…",
    resetDemoHistory: "Reset demo history",
    resetDemoReady:
      "Clears only this preview's in-memory workspace activity. Reloading restores the demo. Repository files and Git are not connected or changed.",
    resetDemoConfirmTitle: "Reset this preview's demo history?",
    resetDemoConfirmBody:
      "This clears only in-memory activity for the selected demo workspace. Reloading restores the bundled demo. No repository files, commits, or branches are connected or changed.",
    resetDemoConfirm: "Reset demo",
    resetDemoInProgress: "Resetting…",
    localPreview:
      "Preview preference · not persisted to the native settings service",
  },
  createWorkspace: {
    title: "Create workspace",
    firstTitle: "Create your first workspace",
    description:
      "Creates a Git worktree for the selected project on a new app-managed branch.",
    project: "Project",
    name: "Workspace name",
    cancel: "Cancel",
    create: "Create workspace",
    creating: "Creating…",
  },
  compactSidebar: "Open workspace navigation",
}

const ja: typeof en = {
  ...en,
  workspaces: "ワークスペース",
  filterWorkspaces: "ワークスペースを絞り込む",
  addProject: "プロジェクトを追加",
  addWorkspace: "ワークスペースを追加",
  archiveWorkspace: "ワークスペースをアーカイブ",
  settings: "設定",
  appSettings: "アプリ設定",
  repositoryBreadcrumb: "リポジトリの現在地",
  workspaceActions: "ワークスペース操作",
  workspaceHealth: {
    ready: "リポジトリ準備完了",
    missing: "リポジトリが見つかりません",
    changed: "リポジトリの実体が変わりました",
    unreadable: "リポジトリを読み取れません",
    read_only: "リポジトリは読み取り専用です",
    stale_branch: "アプリ外でブランチが変わりました",
  },
  workspaceMenu: {
    cancel: "ワークスペースを中止",
    cancelDescription: "作業を止め、レビュー用の履歴は保持します。",
    repair: "リポジトリを再選択…",
    repairDescription: "リポジトリを選び直し、ローカルアクセスを修復します。",
    recheckRepository: "リポジトリを再確認",
    recheckDescription:
      "現在のブランチとHEADを読み取り専用で確認し、明示的に使用します。",
    unregister: "プロジェクトの登録を解除…",
    unregisterDescription: "履歴を削除せず、プロジェクトを非表示にします。",
    runningBlocked: "ターンの実行中は操作できません。",
    cancelTitle: "このワークスペースを中止しますか？",
    cancelBody:
      "アプリ内の状態を「中止」に変更します。ソースファイル、worktree、Git ref、履歴は保持します。",
    cancelRunningBody:
      "先に進行中のターンを停止します。対象ターンの終了状態を確認し、ローカル後処理が完了した後だけワークスペースの状態を「中止」に変更します。",
    keepWorkspace: "戻る",
    confirmCancel: "ワークスペースを中止",
    stopAndCancel: "停止して中止",
    unregisterTitle: "このプロジェクトの登録を解除しますか？",
    unregisterBody:
      "このプロジェクトの全ワークスペースがナビゲーションから消えます。ソースファイル、worktree、Git ref、下書き、履歴は削除しません。",
    continueUnregister: "続ける",
    unregisterFinalTitle: "プロジェクト登録の解除を確認",
    unregisterFinalBody:
      "アプリの有効なプロジェクト登録だけを解除します。後で同じリポジトリを再登録すると、保持された履歴を復元できます。",
    confirmUnregister: "プロジェクト登録を解除",
    working: "処理中…",
    error: {
      generic:
        "ワークスペース操作を完了できませんでした。ソースやGitの状態は変更していません。",
      active:
        "プロジェクトはまだ実行中です。修復や登録解除の前に進行中のターンを停止してください。",
      unavailable: "現在の実行環境ではこの操作を利用できません。",
      conflict:
        "別の操作でワークスペースが更新されました。再読み込みしてからお試しください。",
      rootInUse: "そのリポジトリは別のプロジェクトに登録済みです。",
      draft:
        "最新の下書きを保存できなかったため、プロジェクト登録を解除しませんでした。",
    },
  },
  archiveDialog: {
    title: "このワークスペースをアーカイブしますか？",
    body: (workspace: string) =>
      `${workspace} のGit worktreeとアプリ内履歴を削除します。プロジェクトのリポジトリとブランチは保持します。`,
    cancel: "ワークスペースを保持",
    confirm: "ワークスペースをアーカイブ",
    working: "アーカイブ中…",
  },
  workspaceSwitch: {
    title: "停止してワークスペースを切り替えますか？",
    description:
      "現在のワークスペースは、対象ターンの中断、終了状態の確認、ローカル後処理が完了するまで選択中のままです。",
    from: "現在のワークスペース",
    to: "切り替え先",
    goBack: "戻る",
    confirm: "停止して切り替え",
    stopping: "停止して切り替え中…",
    failed:
      "ターンの停止と後処理を完了できませんでした。現在のワークスペースを維持し、下書きと選択は変更していません。",
  },
  dismiss: "閉じる",
  switchWorkspace: "ワークスペースを切り替える",
  repository: "リポジトリ",
  branch: "ブランチ",
  active: "選択中",
  noMatches: "条件に一致するワークスペースはありません。",
  loadingWorkspacesTitle: "ワークスペース履歴を復元中",
  loadingWorkspacesDescription:
    "変更を有効にする前にローカルのワークスペース記録を確認しています。",
  workspaceLoadFailedTitle: "ワークスペース履歴を復元できませんでした",
  workspaceLoadFailedDescription:
    "デモデータへの置き換えは行っていません。安全に続行するにはローカル履歴を再確認してください。",
  clearFilter: "フィルターを解除",
  lifecycle: {
    done: "完了",
    in_review: "レビュー可能",
    in_progress: "実行中",
    backlog: "未着手",
    canceled: "中止",
  },
  attention: {
    needs_answer: "回答待ち",
    approval_required: "承認待ち",
    test_failed: "テスト失敗",
    high_risk: "高リスク",
  },
  tabs: {
    chat: "チャット",
    commit: "コミット",
    settings: "設定",
  },
  connection: {
    checking: "実行環境を確認中",
    preview: "プレビューのみ",
    offline: "オフライン",
    ready: "準備完了",
  },
  previewNoticeTitle: "デザインプレビュー",
  previewNotice:
    "Codex、Git、ローカル履歴は未接続です。同梱Live2Dの描画状態は別に実測表示します。",
  previewNoticeWithHistory:
    "CodexとGitは未接続です。ローカルのワークスペース履歴は永続化され、利用できます。",
  previewNoticeWithEphemeralHistory:
    "CodexとGitは未接続です。デモ用ワークスペースのアクティビティはメモリ内だけに保持され、このプレビューを再起動するとリセットされます。",
  interactiveDemoNotice:
    "決定論的Codex App Serverデモへ接続中です。Gitは未接続で、アクティビティはメモリ内だけに保持され、プレビュー再起動時にリセットされます。",
  runtimeErrorTitle: "ローカル実行環境へ接続できませんでした",
  runtimeErrorDescription:
    "下書きとローカル表示状態は保持されています。実行環境を再確認するか、診断を確認してください。",
  retry: "再試行",
  diagnostics: "診断",
  timelineTitle: "アクティビティ",
  timelineDescription: "構造化・秘匿化されたワークスペースイベント",
  lastSummaryTitle: "前回セッションの要約",
  lastSummaryDescription:
    "このワークスペースの秘匿化済みローカル履歴から復元しました。",
  previewBadge: "参照プレビュー",
  persistedBadge: "ローカルに永続化済み",
  ephemeralHistoryBadge: "デモ用メモリ",
  historyUnavailable: "履歴の復旧が必要です",
  timelineEmptyTitle: "永続化されたアクティビティはまだありません",
  timelineEmptyBody:
    "最初のターンを開始するか、続行前にプロジェクト診断を確認してください。",
  timelineEvent: {
    kind: {
      thread: "Codexセッション",
      turn: "ターン",
      user: "あなた",
      assistant: "Codex",
      plan: "計画を更新",
      tool: "ツール実行",
      file: "ファイル変更",
      diff: "差分を更新",
      decision: "判断",
      approval: "承認",
      request_resolved: "回答を記録",
      error: "操作に失敗",
      completion: "ターン完了",
      status: "アクティビティ",
    },
    history: "記録済みイベント",
    running: "実行中",
    streaming: "応答中",
    interrupted: "中断済み",
    effort: "推論強度",
    attachments: "件の添付",
    decisionRequired: "判断が必要です",
    approvalRequired: "承認が必要です",
    responseNeeded: "Codexは範囲を限定した回答を待っています。",
    waitingForYou: "回答待ち",
    responded: "回答済み",
    operation: "操作",
    target: "対象",
    effect: "実行されること",
    scope: "範囲",
    risk: "リスク",
    reversibility: "可逆性",
    recommendation: "推奨",
    uncertainty: "不確実性",
    evidence: "根拠",
    noRecommendation: "推奨なし",
    decisionEffect: {
      execute_command: "コマンドを実行",
      apply_file_change: "ファイル変更を適用",
      grant_permissions: "要求された権限を付与",
      continue_turn: "進行中のターンを続行",
    },
    scopeValue: {
      command: "このコマンド",
      turn: "このターン",
    },
    riskValue: {
      low: "低",
      medium: "中",
      high: "高",
    },
    reversibilityValue: {
      reversible: "元に戻せます",
      partially_reversible: "一部のみ元に戻せます",
      not_reversible: "元に戻せません",
      unknown: "不明",
    },
    uncertaintyValue: {
      none: "なし",
      limited_context: "判断材料が限定的",
      unknown_effects: "影響が不明",
    },
    answer: "回答を送信",
    submitting: "送信中…",
    other: "その他",
    otherDescription: "範囲を限定した別の回答を入力します。",
    otherAnswer: "その他の回答",
    otherPlaceholder: "1〜2,000文字で入力",
    hold: "判断を保留",
    held: "保留しました。回答は送信されず、このターンは待機中です。",
    interrupt: "ターンを中断",
    interruptDialogTitle: "このターンを中断しますか？",
    interruptDialogDescription:
      "Codexの進行中のターンを停止します。完了済みのワークスペース変更はレビュー用に残ります。",
    interruptDialogCancel: "実行を続ける",
    interruptDialogConfirm: "ターンを中断",
    interrupting: "中断中…",
    interruptFailed:
      "ターンを中断できませんでした。実行中の可能性があります。もう一度お試しください。",
    approvalDecision: {
      approve_once: "今回のみ承認",
      reject: "拒否",
      stop: "ターンを停止",
    },
    copyDetails: "安全な詳細をコピー",
    copy: "コピー",
    copied: "コピー済み",
    copyFailed: "コピー失敗",
    latest: "最新へ",
    newUpdates: "新しい更新",
  },
  tool: "ツール",
  completed: "完了",
  failed: "失敗",
  expandDetails: "安全な詳細を表示",
  collapseDetails: "詳細を閉じる",
  assistantPreview:
    "デスクトップ作業面は統合可能な状態です。このプレビューは実Codexセッションの成功を主張せず、イベント階層だけを示します。",
  verificationPreview:
    "フロントエンドの検証は、名称、終了結果、所要時間、対応コミットへの導線を持つ証拠として提示できます。",
  errorTitle: "接続が必要です",
  errorBody:
    "ローカルCodexの事前診断が成功するまで送信は無効です。下書きは変更されません。",
  decisionTitle: "レビュー境界のプレビュー",
  decisionQuestion: "次の作業単位をどの範囲にしますか？",
  decisionWhy:
    "実装を続ける前に小さく区切ると、証拠とmain sessionのコミットをレビュー可能に保てます。",
  decisionOptionSmall: "レビュー可能な1単位にする",
  decisionOptionSmallImpact:
    "一つの限定された変更を完了・検証してから続けます。",
  decisionOptionHold: "レビューまで保留する",
  decisionOptionHoldImpact: "sourceやGit状態を変更せず待機します。",
  decisionRecommendation: "推奨: レビュー可能な1単位",
  decisionUncertainty: "プレビューモードでは実際の判断要求は発生していません。",
  answerPreview: "プレビュー回答を保存",
  answerSaved: "プレビュー回答をローカルに保存しました",
  composerPlaceholder: "Codexに計画、実装、説明、修正を依頼…",
  composerHint:
    "ファイルや画像を添付 · スクリーンショットを貼り付け · ファイルをドロップ · @でコンテキストを参照",
  add: "追加",
  context: "コンテキスト",
  filesFolders: "ファイルとフォルダー",
  gitDiff: "Git差分",
  terminalOutput: "ターミナル出力",
  model: "GPT-5.6 Sol",
  fixedModel: "固定モデル",
  draftItems: "下書き項目",
  reasoningEffort: "推論強度",
  effortAvailability: {
    none: "現在利用できる推論強度はありません。",
    fast: "この実行環境では高速推論を利用できません。",
    max: "この実行環境では最大推論を利用できません。",
  },
  fast: "高速",
  max: "最大",
  send: "送信",
  stop: "停止",
  commandSend: "⌘↵ 送信",
  removeAttachment: "添付を削除",
  attachmentRejected:
    "25 MiBを超えるファイルは表示を残しますが送信できません。",
  sendUnavailable: "Codexは未接続です。下書きは保持されます。",
  sendEmpty: "指示を入力するか、有効なコンテキストを追加してください。",
  sendBusy: "現在のturnを完了するか、停止してください。",
  pickerUnavailable:
    "このプレビューではnative操作が未接続です。ローカルproject状態は変更していません。",
  contextUnavailable:
    "コンテキスト取得にはnative workspace adapterが必要です。下書きは変更していません。",
  character: {
    rendererPending: "Live2D rendererを起動中",
    rendererDescription:
      "アプリ管理Live2D rendererの検証済み状態と安全なfallbackを表示します。",
    externalRenderer: "外部renderer · 状態は取得できません",
    retryRenderer: "Live2Dを再試行",
    state: "コンパニオン状態",
    disconnected: "切断中",
    semanticState: {
      idle: "待機中",
      thinking: "考え中",
      acting: "実行中",
      waiting_for_user: "回答待ち",
      reviewing: "レビュー中",
      error: "エラー",
      completed: "完了",
      disconnected: "切断中",
    },
    muted: "ミュート中",
    unmuted: "音声利用可能",
    mute: "コンパニオンをミュート",
    unmute: "コンパニオンのミュートを解除",
  },
  contextView: {
    title: "プロジェクトコンテキスト",
    description:
      "Codexへ渡すプロジェクト固有の指示です。変更は次のturnから適用します。",
    projectTitle: "プロジェクトコンテキスト",
    projectDescription: "Codexへ渡す目標、制約、完了条件です。",
    characterTitle: "キャラクターコンテキスト",
    characterDescription: "技術policyを上書きできない口調と表現設定です。",
    goal: "目標",
    constraints: "制約",
    definition: "完了条件",
    displayName: "表示名",
    tone: "口調",
    prohibited: "禁止表現",
    saveProject: "プロジェクトコンテキストを保存",
    saveCharacter: "Character下書きを保存",
    localOnly:
      "プロジェクトコンテキストservice接続まではローカル表示状態だけに保持します。",
    version: "バージョン",
    nextTurn: "次のturnから適用",
    conflictTitle: "新しいバージョンが保存されています",
    conflictVersions:
      "この下書きはv{local}から編集され、保存済みcontextはv{remote}です。",
    changedFields: "差分のある項目:",
    reloadCurrent: "保存済みバージョンを再読込",
    saveError: "コンテキストを保存できませんでした",
    saveErrorDescription:
      "下書きは保持されています。詳細を確認して再試行してください。",
    errors: {
      required: "保存する前に値を入力してください。",
      text: "文字数上限を超えているか、使用できない制御文字が含まれています。",
      items: "項目数と各項目の文字数上限を確認してください。",
      technicalReference:
        "正規化されたプロジェクト相対パスか、対応する文書参照を指定してください。",
      policy: "キャラクター表現から技術policyや安全policyは変更できません。",
      total: "コンテキスト全体の文字数上限を超えています。",
      referenceBoundary:
        "技術参照は登録済みプロジェクト内で解決できる必要があります。",
      referenceMissing:
        "保存済みの技術参照を利用できません。確認してから保存し直してください。",
      referenceChanged:
        "保存済みの技術参照が別の対象を指しています。確認してから保存し直してください。",
    },
    savedNextTurn: "保存しました。次のturnからこのバージョンを使います。",
    loading: "プロジェクトコンテキストを読込中",
    unsaved: "未保存",
    technicalReferences: "技術参照",
    onePerLine: "1行に1項目",
    referencesDescription:
      "プロジェクト内の相対パスのみ指定できます。policyファイルや範囲外のパスは拒否します。",
    userNotes: "ユーザーメモ",
    toneNotes: "口調メモ",
    speechDensity: "発話密度",
    concise: "簡潔",
    warm: "温かい",
    neutral: "中立",
    quiet: "控えめ",
    keyEvents: "要点のみ",
    detailed: "詳細",
    behavior: "振る舞い",
    policyBoundary: "表現設定は技術policyや安全policyを上書きできません",
    total: "{count} / {maximum}文字",
    runningTurnUnaffected:
      "実行中のturnは取得済みバージョンを維持し、変更は次のturnから反映します。",
    discard: "下書きを破棄",
    saving: "保存中…",
  },
  settingsView: {
    appTitle: "アプリ設定",
    appDescription:
      "すべてのプロジェクトに共通するキャラクター、コンパニオン、設定、診断です。",
    projectTitle: "プロジェクト設定",
    projectDescription: (project: string) => `${project} の設定です。`,
    workspaceTitle: "ワークスペース設定",
    workspaceDescription: (workspace: string) =>
      `${workspace} の履歴とプライバシーを管理します。`,
    backToWorkspace: "ワークスペースへ戻る",
    backToProjects: "プロジェクト一覧へ戻る",
    sections: {
      general: "一般",
      projects: "プロジェクト",
      project_context: "プロジェクトコンテキスト",
      character_context: "キャラクターコンテキスト",
      companion: "コンパニオン",
      audio: "音声",
      diagnostics: "診断",
      history: "履歴とプライバシー",
    },
    generalTitle: "一般",
    projectsTitle: "登録済みプロジェクト",
    projectsDescription:
      "プロジェクトを開くと、所属ワークスペースで共有するコンテキストを管理できます。登録解除はこのアプリ内だけに反映されます。",
    projectContextDescription: (workspaceCount: string) =>
      `このプロジェクトの${workspaceCount}で共有するコンテキストです。`,
    noProjectsTitle: "登録済みプロジェクトはありません",
    noProjectsDescription:
      "サイドバーのフォルダボタンからGitリポジトリを登録してください。",
    workspaceCount: (count: number) =>
      `${count.toLocaleString()}件のワークスペース`,
    unregisterProject: "登録解除",
    unregisterProjectTitle: "このプロジェクトの登録を解除しますか？",
    unregisterProjectBody: (project: string) =>
      `${project} をこのアプリから非表示にします。リポジトリ、worktree、ブランチ、ファイルはディスク上に保持します。`,
    keepProject: "プロジェクトを保持",
    confirmUnregisterProject: "プロジェクト登録を解除",
    unregisteringProject: "登録解除中…",
    language: "言語",
    languageDescription:
      "設定ストアが変更を受理すると、すべてのアプリ管理文言へ即時に反映します。",
    languageSaveError:
      "言語を保存できませんでした。以前の言語を維持しています。",
    preferenceStatusNative: "ネイティブ設定",
    preferenceStatusDemo:
      "デモ用メモリ · このプレビューを再起動すると初期値に戻ります",
    preferenceVersion: "バージョン",
    preferenceSaving: "設定を保存中…",
    preferenceRecoveryTitle: "設定の復旧が必要です",
    preferenceRecoveryBody:
      "安全な初期値を使用しています。読み取れない値は表示も適用もしていません。",
    preferenceErrorTitle: "設定を保存できませんでした",
    preferenceErrorBody:
      "最後に保存できた設定を維持しています。変更を再試行するか、設定レコードだけをリセットしてください。",
    preferenceSafeCode: "安全なコード",
    motion: "動きを減らす",
    motionDescription: "OSが動きの削減を要求している場合は常に優先します。",
    system: "システム",
    reduce: "減らす",
    allow: "許可",
    characterVisibility: "キャラクター表示",
    characterVisibilityDescription:
      "非表示にすると全ワークスペースのcanvasとGPU animationを停止し、text状態は残します。",
    characterVisible: "キャラクターを表示",
    appVersion: "アプリバージョン",
    resetPreferences: "設定をリセット",
    resetPreferencesDescription:
      "言語をOS初期値、動きをシステム、キャラクターを表示へ戻します。ワークスペース、履歴、Context、モデルライブラリ、Git、音声設定は変更しません。",
    resetPreferencesConfirmTitle: "アプリ設定をリセットしますか？",
    resetPreferencesConfirmBody:
      "AppPreferencesV1だけを置き換えます。ワークスペース、履歴、Context、キャラクターモデルライブラリ、Git状態、音声設定は変わりません。",
    resetPreferencesCancel: "キャンセル",
    resetPreferencesConfirm: "設定をリセット",
    resetPreferencesInProgress: "リセット中…",
    resetUi: "UI状態をリセット",
    resetUiDescription:
      "filterとローカル選択だけを戻します。repositoryと履歴dataは変更しません。",
    companionTitle: "コンパニオン",
    bundledModel: "モデル",
    bundledModelValue: "Hiyori",
    renderer: "Renderer",
    builtinRenderer: "アプリLive2D",
    externalRenderer: "外部renderer",
    bundledVersion: "モデルバージョン",
    provenance: "来歴",
    illustrationCredit: "イラスト",
    modelingCredit: "モデリング",
    noticeHash: "Notice SHA-256",
    phase: "フェーズ",
    fallback: "フォールバック",
    motionPolicy: "モーション方針",
    audioState: "音声",
    lastError: "最後の安全なエラー",
    noRecordedError: "記録なし",
    unknown: "不明",
    characterPhases: {
      idle: "待機中",
      loading: "読込中",
      ready: "準備完了",
      recovering: "復旧中",
      error: "エラー",
      disposed: "停止中",
      hidden: "非表示",
      unknown: "不明",
    },
    characterFallbacks: {
      animated: "アニメーション",
      reduced: "動きを削減",
      static: "静止プレビュー",
      text_only: "テキストのみ",
      unknown: "不明",
    },
    characterPolicies: {
      animated: "アニメーション",
      reduced: "動きを削減",
      hidden: "非表示",
      unknown: "不明",
    },
    live2dStatus: "Live2D",
    live2dLoading: "読込中",
    live2dReady: "準備完了",
    live2dRecovering: "復旧中",
    live2dDegraded: "縮退中",
    live2dError: "エラー",
    live2dHidden: "非表示",
    live2dUnknown: "不明",
    characterErrorIntro:
      "コンパニオンは安全に縮退しました。ワークスペース操作は継続できます。",
    retryCharacter: "Live2Dを再試行",
    importModel: "モデルをimport",
    hideCharacter: "キャラクターを非表示",
    hideCharacterDescription:
      "visual stageを停止し、semantic text状態は残します。",
    audioTitle: "音声",
    tts: "TTSを有効化",
    ttsDescription:
      "初期値はoffです。このUI previewから外部requestは行いません。",
    mute: "ミュート",
    rate: "読み上げ速度",
    diagnosticsTitle: "診断",
    recheck: "実行環境を再確認",
    runtimeMode: "実行モード",
    platform: "プラットフォーム",
    integrations: "連携準備状況",
    notConfigured: "未構成",
    localHistory: "ローカル履歴",
    historyReadOnly: "読み取り専用",
    historyEphemeral: "デモ用メモリ",
    historyTitle: "履歴とプライバシー",
    stored: "ローカルに保存",
    storedBody:
      "ワークスペースのメタデータ、正規化済みイベント、下書き、コンテキスト、証拠パック。",
    storedEphemeral: "デモ用メモリに保持",
    storedEphemeralBody:
      "ワークスペースのメタデータ、アクティビティ、下書き、コンテキスト、証拠はこのプレビューの間だけ保持されます。再読み込みすると同梱デモに戻ります。",
    neverStored: "保存しない",
    neverStoredBody:
      "推論の生データ、生成音声、コミット説明の入出力、秘匿情報の生データ。",
    deleteHistory: "ワークスペース履歴を削除",
    deleteDisabled: "履歴サービスは未接続です。何も削除していません。",
    deleteReady:
      "このワークスペースのアプリ内メタデータとイベントを削除します。リポジトリのファイル、コミット、ブランチは変更しません。",
    deleteConfirmTitle: "このワークスペースの履歴を削除しますか？",
    deleteConfirmBody:
      "選択中のワークスペースに属するローカルアプリ履歴だけを削除します。この操作は元に戻せません。",
    deleteCancel: "キャンセル",
    deleteConfirm: "履歴を削除",
    deleteInProgress: "削除中…",
    resetDemoHistory: "デモ履歴をリセット",
    resetDemoReady:
      "現在のプレビューにあるメモリ内アクティビティだけを消去します。再読み込みするとデモに戻ります。リポジトリとGitは未接続で、変更されません。",
    resetDemoConfirmTitle: "このプレビューのデモ履歴をリセットしますか？",
    resetDemoConfirmBody:
      "選択中のデモ用ワークスペースにあるメモリ内アクティビティだけを消去します。再読み込みすると同梱デモに戻ります。リポジトリのファイル、コミット、ブランチは未接続で、変更されません。",
    resetDemoConfirm: "デモをリセット",
    resetDemoInProgress: "リセット中…",
    localPreview: "プレビュー設定 · native settings serviceには未保存",
  },
  createWorkspace: {
    title: "ワークスペースを作成",
    firstTitle: "最初のワークスペースを作成",
    description:
      "選択したプロジェクトに、アプリ管理の新しいブランチとGit worktreeを作成します。",
    project: "プロジェクト",
    name: "ワークスペース名",
    cancel: "キャンセル",
    create: "ワークスペースを作成",
    creating: "作成中…",
  },
  compactSidebar: "ワークスペースnavigationを開く",
}

export type WorkspaceCopy = typeof en

export function getWorkspaceCopy(locale: SupportedLocale): WorkspaceCopy {
  return locale === "ja" ? ja : en
}
