import type { SupportedLocale } from "@/features/localization"

const en = {
  workspaces: "Workspaces",
  filterWorkspaces: "Filter workspaces",
  addProject: "Add project",
  addWorkspace: "Add workspace",
  settings: "Settings",
  appMark: "Coding Wife workspace",
  workspaceActions: "Workspace actions",
  dismiss: "Dismiss",
  switchWorkspace: "Switch workspace",
  repository: "Repository",
  branch: "Branch",
  active: "Active",
  noMatches: "No workspaces match this filter.",
  loadingWorkspacesTitle: "Restoring workspace history",
  loadingWorkspacesDescription:
    "Checking local workspace records before enabling changes.",
  workspaceLoadFailedTitle: "Workspace history could not be restored",
  workspaceLoadFailedDescription:
    "Demo data was not substituted. Retry the local history check to continue safely.",
  clearFilter: "Clear filter",
  lifecycle: {
    done: "Done",
    in_review: "In review",
    in_progress: "In progress",
    backlog: "Backlog",
    canceled: "Canceled",
  },
  attention: {
    needs_answer: "Needs answer",
    approval_required: "Approval required",
    test_failed: "Test failed",
    high_risk: "High risk",
  },
  tabs: {
    chat: "Chat",
    commit: "Commit",
    context: "Context",
    settings: "Settings",
  },
  connection: {
    checking: "Checking runtime",
    preview: "Preview only",
    offline: "Offline",
    ready: "Ready",
  },
  previewNoticeTitle: "Design preview",
  previewNotice:
    "Codex, Git, and local history are not connected. The bundled Live2D companion reports its renderer state separately.",
  previewNoticeWithHistory:
    "Codex and Git are not connected. Local workspace history is persisted and available.",
  previewNoticeWithEphemeralHistory:
    "Codex and Git are not connected. Demo workspace activity is kept in memory and resets when this preview restarts.",
  interactiveDemoNotice:
    "The deterministic Codex App Server demo is connected. Git remains disconnected; activity stays in memory and resets when this preview restarts.",
  runtimeErrorTitle: "The local runtime could not be reached",
  runtimeErrorDescription:
    "Your draft and local view state are preserved. Retry the runtime check or review Diagnostics.",
  retry: "Retry",
  diagnostics: "Diagnostics",
  timelineTitle: "Activity",
  timelineDescription: "Structured, redacted workspace events",
  previewBadge: "Reference preview",
  persistedBadge: "Persisted locally",
  ephemeralHistoryBadge: "Demo memory",
  historyUnavailable: "History requires recovery",
  timelineEmptyTitle: "No persisted activity yet",
  timelineEmptyBody:
    "Start the first turn or inspect project diagnostics before continuing.",
  timelineEvent: {
    kind: {
      thread: "Codex session",
      turn: "Turn",
      user: "You",
      assistant: "Codex",
      plan: "Plan updated",
      tool: "Tool run",
      file: "File change",
      diff: "Diff updated",
      decision: "Decision",
      approval: "Approval",
      request_resolved: "Response recorded",
      error: "Action failed",
      completion: "Turn completed",
      status: "Activity",
    },
    history: "Recorded event",
    running: "Running",
    streaming: "Responding",
    interrupted: "Interrupted",
    effort: "Effort",
    attachments: "attachments",
    decisionRequired: "Your decision is needed",
    approvalRequired: "Approval required",
    responseNeeded: "Codex is waiting for a bounded response.",
    waitingForYou: "Waiting for you",
    responded: "Responded",
    operation: "Operation",
    target: "Target",
    scope: "Scope",
    risk: "Risk",
    reversibility: "Reversibility",
    recommendation: "Recommendation",
    evidence: "Evidence",
    answer: "Send answer",
    submitting: "Sending…",
    other: "Other",
    otherDescription: "Provide a different bounded answer.",
    otherAnswer: "Other answer",
    otherPlaceholder: "Enter 1–2,000 characters",
    hold: "Hold decision",
    held: "Held. No response was sent; this turn is still waiting.",
    interrupt: "Interrupt turn",
    approvalDecision: {
      approve_once: "Approve once",
      reject: "Reject",
      stop: "Stop turn",
    },
    copyDetails: "Copy safe details",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Copy failed",
    latest: "Latest",
    newUpdates: "New updates",
  },
  tool: "Tool",
  completed: "Completed",
  failed: "Failed",
  expandDetails: "Show safe details",
  collapseDetails: "Hide details",
  assistantPreview:
    "The desktop work surface is ready for integration. This preview demonstrates the event hierarchy without claiming a live Codex session.",
  verificationPreview:
    "Frontend checks can be presented as named evidence with a terminal result, duration, and a link to the corresponding checkpoint.",
  errorTitle: "Connection required",
  errorBody:
    "Sending remains blocked until the local Codex preflight succeeds. The draft is kept unchanged.",
  decisionTitle: "Review boundary preview",
  decisionQuestion: "How should the next work unit be scoped?",
  decisionWhy:
    "A smaller unit keeps the evidence and recovery point reviewable before implementation continues.",
  decisionOptionSmall: "Keep one reviewable unit",
  decisionOptionSmallImpact:
    "Complete one bounded change and verify it before continuing.",
  decisionOptionHold: "Hold for review",
  decisionOptionHoldImpact: "Pause without changing source or Git state.",
  decisionRecommendation: "Recommended: one reviewable unit",
  decisionUncertainty: "No live decision request is active in preview mode.",
  answerPreview: "Save preview answer",
  answerSaved: "Preview answer saved locally",
  composerPlaceholder: "Ask Codex to plan, build, explain, or fix anything…",
  composerHint:
    "Attach files or images · paste a screenshot · drag files here · use @ to reference context",
  add: "Add",
  context: "Context",
  filesFolders: "Files & folders",
  gitDiff: "Git diff",
  terminalOutput: "Terminal output",
  model: "GPT-5.6 Sol",
  fast: "Fast",
  max: "Max",
  send: "Send",
  stop: "Stop",
  commandSend: "⌘↵ send",
  removeAttachment: "Remove attachment",
  attachmentRejected: "Files over 25 MiB remain visible but cannot be sent.",
  sendUnavailable: "Codex is not connected. Your draft will be preserved.",
  sendEmpty: "Enter an instruction or attach valid context.",
  sendBusy: "Wait for the current turn to finish or stop it.",
  pickerUnavailable:
    "The native operation is not connected in this preview. No local project state changed.",
  contextUnavailable:
    "Context capture requires the native workspace adapter. The draft was not changed.",
  character: {
    rendererPending: "Starting Live2D renderer",
    rendererDescription:
      "The app-owned Live2D renderer reports verified status and safe fallback details here.",
    externalRenderer: "External renderer · status unavailable",
    retryRenderer: "Retry Live2D",
    state: "Companion state",
    disconnected: "Disconnected",
    muted: "Muted",
    unmuted: "Audio available",
    mute: "Mute companion",
    unmute: "Unmute companion",
  },
  commit: {
    title: "Session evidence",
    description:
      "Checkpoint evidence appears here only after Scope, Ownership, Verification, and Risk have terminal results.",
    emptyTitle: "No persisted checkpoint evidence",
    emptyDescription:
      "The preview transport has not created a Git object or review pack.",
    backToChat: "Back to Chat",
    gateSummary: "Checkpoint gates",
    unavailable: "Unavailable",
    gates: ["Scope", "Ownership", "Verification", "Risk"],
    listTitle: "Checkpoints",
    noCheckpoint: "No checkpoint",
    detailTitle: "Evidence detail",
    detailBody:
      "Connect local history and Git services to inspect sanitized diffs, decisions, failed attempts, risks, and recovery actions.",
  },
  contextView: {
    title: "Workspace context",
    description:
      "Project instructions and companion presentation remain separate. Changes apply from the next turn.",
    projectTitle: "Project context",
    projectDescription: "Goals, constraints, and definition of done for Codex.",
    characterTitle: "Character context",
    characterDescription:
      "Tone and presentation preferences that cannot override technical policy.",
    goal: "Goal",
    constraints: "Constraints",
    definition: "Definition of done",
    displayName: "Display name",
    tone: "Tone",
    prohibited: "Prohibited expressions",
    saveProject: "Save project draft",
    saveCharacter: "Save character draft",
    localOnly: "Held locally until the workspace history service is connected.",
    version: "Version",
    nextTurn: "Applies from the next turn",
  },
  settingsView: {
    title: "Settings & diagnostics",
    description:
      "Local preferences, safety boundaries, and integration readiness.",
    sections: {
      general: "General",
      project_context: "Project context",
      character_context: "Character context",
      companion: "Companion",
      audio: "Audio",
      support: "Support",
      diagnostics: "Diagnostics",
      history: "History & privacy",
    },
    generalTitle: "General",
    language: "Language",
    languageDescription:
      "Changes app-owned copy immediately and persists when the locale store accepts it.",
    languageSaveError:
      "The language could not be saved. The previous language is unchanged.",
    motion: "Reduced motion",
    motionDescription:
      "System preference always takes precedence when reduction is requested.",
    system: "System",
    reduce: "Reduce",
    allow: "Allow",
    appVersion: "App version",
    resetUi: "Reset UI state",
    resetUiDescription:
      "Resets filters and local view selections. Repository and history data are not changed.",
    companionTitle: "Companion",
    bundledModel: "Model",
    bundledModelValue: "Hiyori",
    renderer: "Renderer",
    builtinRenderer: "App Live2D",
    externalRenderer: "External renderer",
    bundledVersion: "Model version",
    provenance: "Provenance",
    illustrationCredit: "Illustration",
    modelingCredit: "Modeling",
    noticeHash: "Notice SHA-256",
    phase: "Phase",
    fallback: "Fallback",
    motionPolicy: "Motion policy",
    audioState: "Audio",
    lastError: "Last safe error",
    noRecordedError: "None recorded",
    unknown: "Unknown",
    characterPhases: {
      idle: "Idle",
      loading: "Loading",
      ready: "Ready",
      recovering: "Recovering",
      error: "Error",
      disposed: "Stopped",
      hidden: "Hidden",
      unknown: "Unknown",
    },
    characterFallbacks: {
      animated: "Animated",
      reduced: "Reduced",
      static: "Static preview",
      text_only: "Text only",
      unknown: "Unknown",
    },
    characterPolicies: {
      animated: "Animated",
      reduced: "Reduced",
      hidden: "Hidden",
      unknown: "Unknown",
    },
    live2dStatus: "Live2D",
    live2dLoading: "Loading",
    live2dReady: "Ready",
    live2dRecovering: "Recovering",
    live2dDegraded: "Degraded",
    live2dError: "Error",
    live2dHidden: "Hidden",
    live2dUnknown: "Unknown",
    characterErrorIntro:
      "The companion fell back safely. Workspace controls remain available.",
    retryCharacter: "Retry Live2D",
    importModel: "Import model",
    hideCharacter: "Hide character",
    hideCharacterDescription:
      "Stops the visual stage while keeping the semantic text state.",
    audioTitle: "Audio",
    tts: "Enable TTS",
    ttsDescription:
      "Off by default. No external request is made by this UI preview.",
    mute: "Mute",
    rate: "Speech rate",
    supportTitle: "Support",
    supportGlobal: "Enable isolated support",
    supportDescription:
      "Requires a proven ephemeral, tool-free runtime. It remains off in preview mode.",
    presence: "Presence narration",
    reviewer: "Checkpoint reviewer",
    diagnosticsTitle: "Diagnostics",
    recheck: "Recheck runtime",
    runtimeMode: "Runtime mode",
    platform: "Platform",
    integrations: "Integration readiness",
    notConfigured: "Not configured",
    localHistory: "Local history",
    historyReadOnly: "Read only",
    historyEphemeral: "Demo memory",
    historyTitle: "History & privacy",
    stored: "Stored locally",
    storedBody:
      "Workspace metadata, normalized events, drafts, context, and evidence packs.",
    storedEphemeral: "Stored in demo memory",
    storedEphemeralBody:
      "Workspace metadata, activity, drafts, context, and evidence exist only for this preview. Reloading restores the bundled demo.",
    neverStored: "Never stored",
    neverStoredBody:
      "Raw reasoning, generated audio, support prompt/response, and raw secrets.",
    deleteHistory: "Delete workspace history",
    deleteDisabled: "No connected history service; nothing was deleted.",
    deleteReady:
      "Deletes this workspace's app metadata and events. Repository files, commits, and branches are never changed.",
    deleteConfirmTitle: "Delete this workspace history?",
    deleteConfirmBody:
      "This removes local app history for the selected workspace only. This action cannot be undone.",
    deleteCancel: "Cancel",
    deleteConfirm: "Delete history",
    deleteInProgress: "Deleting…",
    resetDemoHistory: "Reset demo history",
    resetDemoReady:
      "Clears only this preview's in-memory workspace activity. Reloading restores the demo. Repository files and Git are not connected or changed.",
    resetDemoConfirmTitle: "Reset this preview's demo history?",
    resetDemoConfirmBody:
      "This clears only in-memory activity for the selected demo workspace. Reloading restores the bundled demo. No repository files, commits, or branches are connected or changed.",
    resetDemoConfirm: "Reset demo",
    resetDemoInProgress: "Resetting…",
    localPreview:
      "Preview preference · not persisted to the native settings service",
  },
  createWorkspace: {
    title: "Create workspace",
    description:
      "Creates a Backlog session in the selected project and keeps its goal as the first draft.",
    name: "Workspace name",
    goal: "Goal",
    cancel: "Cancel",
    create: "Create",
  },
  compactSidebar: "Open workspace navigation",
}

const ja: typeof en = {
  ...en,
  workspaces: "ワークスペース",
  filterWorkspaces: "ワークスペースを絞り込む",
  addProject: "プロジェクトを追加",
  addWorkspace: "ワークスペースを追加",
  settings: "設定",
  appMark: "Coding Wifeワークスペース",
  workspaceActions: "ワークスペース操作",
  dismiss: "閉じる",
  switchWorkspace: "ワークスペースを切り替える",
  repository: "リポジトリ",
  branch: "ブランチ",
  active: "選択中",
  noMatches: "条件に一致するワークスペースはありません。",
  loadingWorkspacesTitle: "ワークスペース履歴を復元中",
  loadingWorkspacesDescription:
    "変更を有効にする前にローカルのワークスペース記録を確認しています。",
  workspaceLoadFailedTitle: "ワークスペース履歴を復元できませんでした",
  workspaceLoadFailedDescription:
    "デモデータへの置き換えは行っていません。安全に続行するにはローカル履歴を再確認してください。",
  clearFilter: "フィルターを解除",
  lifecycle: {
    done: "完了",
    in_review: "レビュー可能",
    in_progress: "実行中",
    backlog: "未着手",
    canceled: "中止",
  },
  attention: {
    needs_answer: "回答待ち",
    approval_required: "承認待ち",
    test_failed: "テスト失敗",
    high_risk: "高リスク",
  },
  tabs: {
    chat: "チャット",
    commit: "コミット",
    context: "コンテキスト",
    settings: "設定",
  },
  connection: {
    checking: "実行環境を確認中",
    preview: "プレビューのみ",
    offline: "オフライン",
    ready: "準備完了",
  },
  previewNoticeTitle: "デザインプレビュー",
  previewNotice:
    "Codex、Git、ローカル履歴は未接続です。同梱Live2Dの描画状態は別に実測表示します。",
  previewNoticeWithHistory:
    "CodexとGitは未接続です。ローカルのワークスペース履歴は永続化され、利用できます。",
  previewNoticeWithEphemeralHistory:
    "CodexとGitは未接続です。デモ用ワークスペースのアクティビティはメモリ内だけに保持され、このプレビューを再起動するとリセットされます。",
  interactiveDemoNotice:
    "決定論的Codex App Serverデモへ接続中です。Gitは未接続で、アクティビティはメモリ内だけに保持され、プレビュー再起動時にリセットされます。",
  runtimeErrorTitle: "ローカル実行環境へ接続できませんでした",
  runtimeErrorDescription:
    "下書きとローカル表示状態は保持されています。実行環境を再確認するか、診断を確認してください。",
  retry: "再試行",
  diagnostics: "診断",
  timelineTitle: "アクティビティ",
  timelineDescription: "構造化・秘匿化されたワークスペースイベント",
  previewBadge: "参照プレビュー",
  persistedBadge: "ローカルに永続化済み",
  ephemeralHistoryBadge: "デモ用メモリ",
  historyUnavailable: "履歴の復旧が必要です",
  timelineEmptyTitle: "永続化されたアクティビティはまだありません",
  timelineEmptyBody:
    "最初のターンを開始するか、続行前にプロジェクト診断を確認してください。",
  timelineEvent: {
    kind: {
      thread: "Codexセッション",
      turn: "ターン",
      user: "あなた",
      assistant: "Codex",
      plan: "計画を更新",
      tool: "ツール実行",
      file: "ファイル変更",
      diff: "差分を更新",
      decision: "判断",
      approval: "承認",
      request_resolved: "回答を記録",
      error: "操作に失敗",
      completion: "ターン完了",
      status: "アクティビティ",
    },
    history: "記録済みイベント",
    running: "実行中",
    streaming: "応答中",
    interrupted: "中断済み",
    effort: "推論強度",
    attachments: "件の添付",
    decisionRequired: "判断が必要です",
    approvalRequired: "承認が必要です",
    responseNeeded: "Codexは範囲を限定した回答を待っています。",
    waitingForYou: "回答待ち",
    responded: "回答済み",
    operation: "操作",
    target: "対象",
    scope: "範囲",
    risk: "リスク",
    reversibility: "可逆性",
    recommendation: "推奨",
    evidence: "根拠",
    answer: "回答を送信",
    submitting: "送信中…",
    other: "その他",
    otherDescription: "範囲を限定した別の回答を入力します。",
    otherAnswer: "その他の回答",
    otherPlaceholder: "1〜2,000文字で入力",
    hold: "判断を保留",
    held: "保留しました。回答は送信されず、このターンは待機中です。",
    interrupt: "ターンを中断",
    approvalDecision: {
      approve_once: "今回のみ承認",
      reject: "拒否",
      stop: "ターンを停止",
    },
    copyDetails: "安全な詳細をコピー",
    copy: "コピー",
    copied: "コピー済み",
    copyFailed: "コピー失敗",
    latest: "最新へ",
    newUpdates: "新しい更新",
  },
  tool: "ツール",
  completed: "完了",
  failed: "失敗",
  expandDetails: "安全な詳細を表示",
  collapseDetails: "詳細を閉じる",
  assistantPreview:
    "デスクトップ作業面は統合可能な状態です。このプレビューは実Codexセッションの成功を主張せず、イベント階層だけを示します。",
  verificationPreview:
    "フロントエンドの検証は、名称、終了結果、所要時間、対応checkpointへの導線を持つ証拠として提示できます。",
  errorTitle: "接続が必要です",
  errorBody:
    "ローカルCodexの事前診断が成功するまで送信は無効です。下書きは変更されません。",
  decisionTitle: "レビュー境界のプレビュー",
  decisionQuestion: "次の作業単位をどの範囲にしますか？",
  decisionWhy:
    "実装を続ける前に小さく区切ると、証拠と復元地点をレビュー可能に保てます。",
  decisionOptionSmall: "レビュー可能な1単位にする",
  decisionOptionSmallImpact:
    "一つの限定された変更を完了・検証してから続けます。",
  decisionOptionHold: "レビューまで保留する",
  decisionOptionHoldImpact: "sourceやGit状態を変更せず待機します。",
  decisionRecommendation: "推奨: レビュー可能な1単位",
  decisionUncertainty: "プレビューモードでは実際の判断要求は発生していません。",
  answerPreview: "プレビュー回答を保存",
  answerSaved: "プレビュー回答をローカルに保存しました",
  composerPlaceholder: "Codexに計画、実装、説明、修正を依頼…",
  composerHint:
    "ファイルや画像を添付 · スクリーンショットを貼り付け · ファイルをドロップ · @でコンテキストを参照",
  add: "追加",
  context: "コンテキスト",
  filesFolders: "ファイルとフォルダー",
  gitDiff: "Git差分",
  terminalOutput: "ターミナル出力",
  model: "GPT-5.6 Sol",
  fast: "高速",
  max: "最大",
  send: "送信",
  stop: "停止",
  commandSend: "⌘↵ 送信",
  removeAttachment: "添付を削除",
  attachmentRejected:
    "25 MiBを超えるファイルは表示を残しますが送信できません。",
  sendUnavailable: "Codexは未接続です。下書きは保持されます。",
  sendEmpty: "指示を入力するか、有効なコンテキストを追加してください。",
  sendBusy: "現在のturnを完了するか、停止してください。",
  pickerUnavailable:
    "このプレビューではnative操作が未接続です。ローカルproject状態は変更していません。",
  contextUnavailable:
    "コンテキスト取得にはnative workspace adapterが必要です。下書きは変更していません。",
  character: {
    rendererPending: "Live2D rendererを起動中",
    rendererDescription:
      "アプリ管理Live2D rendererの検証済み状態と安全なfallbackを表示します。",
    externalRenderer: "外部renderer · 状態は取得できません",
    retryRenderer: "Live2Dを再試行",
    state: "コンパニオン状態",
    disconnected: "切断中",
    muted: "ミュート中",
    unmuted: "音声利用可能",
    mute: "コンパニオンをミュート",
    unmute: "コンパニオンのミュートを解除",
  },
  commit: {
    title: "セッション証拠",
    description:
      "Scope、Ownership、Verification、Riskがterminalになった後だけcheckpoint証拠を表示します。",
    emptyTitle: "永続化済みcheckpoint証拠はありません",
    emptyDescription:
      "プレビューtransportはGit objectやreview packを作成していません。",
    backToChat: "チャットへ戻る",
    gateSummary: "Checkpoint gate",
    unavailable: "利用不可",
    gates: ["Scope", "Ownership", "Verification", "Risk"],
    listTitle: "チェックポイント",
    noCheckpoint: "Checkpointなし",
    detailTitle: "証拠詳細",
    detailBody:
      "ローカル履歴とGit serviceを接続すると、秘匿化された差分、判断、失敗、リスク、復元操作を確認できます。",
  },
  contextView: {
    title: "ワークスペースコンテキスト",
    description:
      "project指示とcompanion表現を分離します。変更は次のturnから適用します。",
    projectTitle: "プロジェクトコンテキスト",
    projectDescription: "Codexへ渡す目標、制約、完了条件です。",
    characterTitle: "キャラクターコンテキスト",
    characterDescription: "技術policyを上書きできない口調と表現設定です。",
    goal: "目標",
    constraints: "制約",
    definition: "完了条件",
    displayName: "表示名",
    tone: "口調",
    prohibited: "禁止表現",
    saveProject: "Project下書きを保存",
    saveCharacter: "Character下書きを保存",
    localOnly:
      "workspace履歴service接続まではローカル表示状態だけに保持します。",
    version: "バージョン",
    nextTurn: "次のturnから適用",
  },
  settingsView: {
    title: "設定・診断",
    description: "ローカル設定、安全境界、連携準備状況を確認します。",
    sections: {
      general: "一般",
      project_context: "プロジェクトコンテキスト",
      character_context: "キャラクターコンテキスト",
      companion: "コンパニオン",
      audio: "音声",
      support: "支援",
      diagnostics: "診断",
      history: "履歴とプライバシー",
    },
    generalTitle: "一般",
    language: "言語",
    languageDescription:
      "アプリ管理文言を即時に切り替え、locale storeが受理した場合だけ永続化します。",
    languageSaveError:
      "言語を保存できませんでした。以前の言語を維持しています。",
    motion: "動きを減らす",
    motionDescription: "OSが動きの削減を要求している場合は常に優先します。",
    system: "システム",
    reduce: "減らす",
    allow: "許可",
    appVersion: "アプリバージョン",
    resetUi: "UI状態をリセット",
    resetUiDescription:
      "filterとローカル選択だけを戻します。repositoryと履歴dataは変更しません。",
    companionTitle: "コンパニオン",
    bundledModel: "モデル",
    bundledModelValue: "Hiyori",
    renderer: "Renderer",
    builtinRenderer: "アプリLive2D",
    externalRenderer: "外部renderer",
    bundledVersion: "モデルバージョン",
    provenance: "来歴",
    illustrationCredit: "イラスト",
    modelingCredit: "モデリング",
    noticeHash: "Notice SHA-256",
    phase: "フェーズ",
    fallback: "フォールバック",
    motionPolicy: "モーション方針",
    audioState: "音声",
    lastError: "最後の安全なエラー",
    noRecordedError: "記録なし",
    unknown: "不明",
    characterPhases: {
      idle: "待機中",
      loading: "読込中",
      ready: "準備完了",
      recovering: "復旧中",
      error: "エラー",
      disposed: "停止中",
      hidden: "非表示",
      unknown: "不明",
    },
    characterFallbacks: {
      animated: "アニメーション",
      reduced: "動きを削減",
      static: "静止プレビュー",
      text_only: "テキストのみ",
      unknown: "不明",
    },
    characterPolicies: {
      animated: "アニメーション",
      reduced: "動きを削減",
      hidden: "非表示",
      unknown: "不明",
    },
    live2dStatus: "Live2D",
    live2dLoading: "読込中",
    live2dReady: "準備完了",
    live2dRecovering: "復旧中",
    live2dDegraded: "縮退中",
    live2dError: "エラー",
    live2dHidden: "非表示",
    live2dUnknown: "不明",
    characterErrorIntro:
      "コンパニオンは安全に縮退しました。ワークスペース操作は継続できます。",
    retryCharacter: "Live2Dを再試行",
    importModel: "モデルをimport",
    hideCharacter: "キャラクターを非表示",
    hideCharacterDescription:
      "visual stageを停止し、semantic text状態は残します。",
    audioTitle: "音声",
    tts: "TTSを有効化",
    ttsDescription:
      "初期値はoffです。このUI previewから外部requestは行いません。",
    mute: "ミュート",
    rate: "読み上げ速度",
    supportTitle: "支援",
    supportGlobal: "分離支援を有効化",
    supportDescription:
      "toolなしのephemeral runtimeを証明する必要があるため、previewではoffを維持します。",
    presence: "状況実況",
    reviewer: "Checkpoint reviewer",
    diagnosticsTitle: "診断",
    recheck: "実行環境を再確認",
    runtimeMode: "実行モード",
    platform: "プラットフォーム",
    integrations: "連携準備状況",
    notConfigured: "未構成",
    localHistory: "ローカル履歴",
    historyReadOnly: "読み取り専用",
    historyEphemeral: "デモ用メモリ",
    historyTitle: "履歴とプライバシー",
    stored: "ローカルに保存",
    storedBody:
      "ワークスペースのメタデータ、正規化済みイベント、下書き、コンテキスト、証拠パック。",
    storedEphemeral: "デモ用メモリに保持",
    storedEphemeralBody:
      "ワークスペースのメタデータ、アクティビティ、下書き、コンテキスト、証拠はこのプレビューの間だけ保持されます。再読み込みすると同梱デモに戻ります。",
    neverStored: "保存しない",
    neverStoredBody:
      "推論の生データ、生成音声、支援用の入出力、秘匿情報の生データ。",
    deleteHistory: "ワークスペース履歴を削除",
    deleteDisabled: "履歴サービスは未接続です。何も削除していません。",
    deleteReady:
      "このワークスペースのアプリ内メタデータとイベントを削除します。リポジトリのファイル、コミット、ブランチは変更しません。",
    deleteConfirmTitle: "このワークスペースの履歴を削除しますか？",
    deleteConfirmBody:
      "選択中のワークスペースに属するローカルアプリ履歴だけを削除します。この操作は元に戻せません。",
    deleteCancel: "キャンセル",
    deleteConfirm: "履歴を削除",
    deleteInProgress: "削除中…",
    resetDemoHistory: "デモ履歴をリセット",
    resetDemoReady:
      "現在のプレビューにあるメモリ内アクティビティだけを消去します。再読み込みするとデモに戻ります。リポジトリとGitは未接続で、変更されません。",
    resetDemoConfirmTitle: "このプレビューのデモ履歴をリセットしますか？",
    resetDemoConfirmBody:
      "選択中のデモ用ワークスペースにあるメモリ内アクティビティだけを消去します。再読み込みすると同梱デモに戻ります。リポジトリのファイル、コミット、ブランチは未接続で、変更されません。",
    resetDemoConfirm: "デモをリセット",
    resetDemoInProgress: "リセット中…",
    localPreview: "プレビュー設定 · native settings serviceには未保存",
  },
  createWorkspace: {
    title: "ワークスペースを作成",
    description:
      "選択中のプロジェクトにBacklogセッションを作成し、目標を最初の下書きとして保存します。",
    name: "ワークスペース名",
    goal: "目標",
    cancel: "キャンセル",
    create: "作成",
  },
  compactSidebar: "ワークスペースnavigationを開く",
}

export type WorkspaceCopy = typeof en

export function getWorkspaceCopy(locale: SupportedLocale): WorkspaceCopy {
  return locale === "ja" ? ja : en
}
